services:
  - type: web
    name: mediwise-api
    env: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
